name: Deploy MCP Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Verify formatting
        run: |
          gofmt -l . | tee /tmp/gofmt.out
          test ! -s /tmp/gofmt.out
      - name: Run tests
        run: go test ./...

  deploy:
    runs-on: ubuntu-latest
    needs: lint-and-test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Build MCP server binary
        run: CGO_ENABLED=0 go build -trimpath -ldflags="-s -w" -o mcpserver ./cmd/mcpserver
      - name: Upload binary to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.MCP_SERVER_HOST }}
          username: ${{ secrets.MCP_SERVER_USER }}
          password: ${{ secrets.MCP_SERVER_PASSWORD }}
          port: 22
          source: mcpserver
          target: /tmp/mcpserver
      - name: Restart MCP service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.MCP_SERVER_HOST }}
          username: ${{ secrets.MCP_SERVER_USER }}
          password: ${{ secrets.MCP_SERVER_PASSWORD }}
          port: 22
          script_stop: true
          script: |
            set -euo pipefail
            sudo install -m 0755 /tmp/mcpserver /usr/local/bin/mcpserver
            sudo systemctl restart mcpserver
            sudo systemctl status mcpserver --no-pager
